# Generated by Django 5.1.2 on 2024-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='hard_spelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='last_successive_successes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='total_fails',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='total_success',
            field=models.IntegerField(default=0),
        ),
    ]
