# Generated by Django 5.1.2 on 2024-10-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_vocab_hard_spelling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='hard_spelling',
            new_name='is_spelling',
        ),
    ]
