# Generated by Django 5.1.2 on 2024-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_rename_hard_spelling_vocab_is_spelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='audio_url',
            field=models.TextField(null=True),
        ),
    ]
